# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='book',
            name='liked',
            field=models.ManyToManyField(related_name='likes', to='likes_books.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to='likes_books.User'),
            preserve_default=False,
        ),
    ]
